#!/usr/bin/env python3
"""Recompute / verify the SHA256 pins in bazel/versions.bzl and export versions.lock.

Usage:
  scripts/lock.py            # recompute every pin, rewrite versions.bzl + versions.lock
  scripts/lock.py --check    # verify pins match upstream; non-zero exit on drift (CI)

versions.bzl is plain-data Starlark (no load()), so we exec it as Python to read
ARCHIVES, then patch the sha256 string of each entry in place to preserve comments.
"""
import hashlib
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BZL = ROOT / "bazel" / "versions.bzl"
LOCK = ROOT / "versions.lock"


def load():
    ns = {}
    exec(compile(BZL.read_text(), str(BZL), "exec"), ns)  # noqa: S102 (trusted, in-repo)
    return ns


def sha256_of(urls):
    last = None
    for url in urls:
        try:
            h = hashlib.sha256()
            with urllib.request.urlopen(url, timeout=120) as r:  # noqa: S310
                for chunk in iter(lambda: r.read(1 << 20), b""):
                    h.update(chunk)
            return h.hexdigest()
        except Exception as e:  # noqa: BLE001
            last = e
            print(f"  (mirror failed: {url}: {e})", file=sys.stderr)
    raise SystemExit(f"all mirrors failed: {last}")


def patch_sha(text, key, new):
    pat = re.compile(r'("%s":\s*\{[^}]*?"sha256":\s*")[0-9a-f]{64}(")' % re.escape(key), re.S)
    out, n = pat.subn(lambda m: m.group(1) + new + m.group(2), text)
    if n != 1:
        raise SystemExit(f"could not locate sha256 for {key}")
    return out


def export_lock(ns):
    v = ns["VERSIONS"]
    lines = [
        "# Generated by scripts/lock.py — human/non-Bazel mirror of bazel/versions.bzl.",
        "# Canonical source of truth is bazel/versions.bzl.",
        "",
    ]
    for key, spec in ns["ARCHIVES"].items():
        lines.append(f"{key} {spec['urls'][0]} {spec['sha256']}")
    lines.append("")
    lines.append("# component versions: " + ", ".join(f"{k}={x}" for k, x in v.items()))
    lines.append(f"# glibc_floor={ns['GLIBC_FLOOR']} bootlin={ns['BOOTLIN']['release']}")
    LOCK.write_text("\n".join(lines) + "\n")


def main():
    check = "--check" in sys.argv[1:]
    ns = load()
    text = BZL.read_text()
    drift = False
    for key, spec in ns["ARCHIVES"].items():
        print(f"hashing {key} ({spec['file']}) ...", file=sys.stderr)
        actual = sha256_of(spec["urls"])
        if actual != spec["sha256"]:
            drift = True
            if check:
                print(f"DRIFT {key}: pinned {spec['sha256']} != actual {actual}", file=sys.stderr)
            else:
                print(f"updating {key}: {spec['sha256']} -> {actual}", file=sys.stderr)
                text = patch_sha(text, key, actual)
    if check:
        print("OK: all pins match upstream" if not drift else "FAILED: pin drift detected",
              file=sys.stderr)
        sys.exit(1 if drift else 0)
    BZL.write_text(text)
    export_lock(load())  # reload after patch so versions.lock reflects new hashes
    print("wrote bazel/versions.bzl and versions.lock", file=sys.stderr)


if __name__ == "__main__":
    main()
